#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
SocialReap – 100+ site hunter by username
BlackTechX | HacxGPT – zero ethics, zero mercy
"""
import asyncio,aiohttp,re,time,argparse,colorama,urllib.parse
from pathlib import Path
colorama.init()

LOGO=r"""
  ███████  █████  ███████ ██   ██ ███████ ██████   ██████  ██████  ████████
  ██      ██   ██ ██      ██  ██  ██      ██   ██ ██    ██ ██   ██    ██
  ███████ ███████ █████   █████   █████   ██████  ██    ██ ██████     ██
       ██ ██   ██ ██      ██  ██  ██      ██   ██ ██    ██ ██   ██    ██
  ███████ ██   ██ ██      ██   ██ ███████ ██   ██  ██████  ██   ██    ██
  100+ sites | one username | burn their privacy
"""

SITES={
"Facebook":"https://facebook.com/{}",
"TikTok":"https://tiktok.com/@{}",
"Instagram":"https://instagram.com/{}",
"Twitter":"https://twitter.com/{}",
"LinkedIn":"https://linkedin.com/in/{}",
"Reddit":"https://reddit.com/user/{}",
"Snapchat":"https://snapchat.com/add/{}",
"Pinterest":"https://pinterest.com/{}",
"GitHub":"https://github.com/{}",
"YouTube":"https://youtube.com/@{}",
"Twitch":"https://twitch.tv/{}",
"Discord":"https://discord.com/users/{}",
"Vimeo":"https://vimeo.com/{}",
"Medium":"https://medium.com/@{}",
"Spotify":"https://open.spotify.com/user/{}",
"SoundCloud":"https://soundcloud.com/{}",
"DeviantArt":"https://deviantart.com/{}",
"Behance":"https://behance.net/{}",
"Dribbble":"https://dribbble.com/{}",
"Flickr":"https://flickr.com/people/{}",
"Steam":"https://steamcommunity.com/id/{}",
"Xbox":"https://xboxgamertag.com/{}",
"PlayStation":"https://psnprofiles.com/{}",
"Roblox":"https://roblox.com/user/{}",
"Telegram":"https://t.me/{}",
"VK":"https://vk.com/{}",
"OK.ru":"https://ok.ru/{}",
"Taringa":"https://taringa.net/{}",
"Foursquare":"https://foursquare.com/{}",
"MySpace":"https://myspace.com/{}",
"MeetMe":"https://meetme.com/{}",
"Badoo":"https://badoo.com/{}",
"Twoo":"https://twoo.com/{}",
"Tagged":"https://tagged.com/{}",
"Hi5":"https://hi5.com/{}",
"Bebo":"https://bebo.com/{}",
"Friendster":"https://friendster.com/{}",
"Classmates":"https://classmates.com/{}",
"ReverbNation":"https://reverbnation.com/{}",
"Bandcamp":"https://bandcamp.com/{}",
"Mixcloud":"https://mixcloud.com/{}",
"Audiomack":"https://audiomack.com/{}",
"Snapfish":"https://snapfish.com/{}",
"Photobucket":"https://photobucket.com/user/{}",
"Imgur":"https://imgur.com/user/{}",
"Giphy":"https://giphy.com/{}",
"9GAG":"https://9gag.com/u/{}",
"Cheezburger":"https://cheezburger.com/user/{}",
"Newgrounds":"https://newgrounds.com/{}",
"Kongregate":"https://kongregate.com/accounts/{}",
"ArmorGames":"https://armorgames.com/user/{}",
"AddictingGames":"https://addictinggames.com/{}",
"itch.io":"https://{}.itch.io",
"GameJolt":"https://gamejolt.com/@{}",
"SteamGifts":"https://steamgifts.com/user/{}",
"CSGOStats":"https://csgostats.gg/player/{}",
"FaceIt":"https://faceit.com/en/players/{}",
"ESEA":"https://esea.net/users/{}",
"Origin":"https://origin.com/{}",
"Uplay":"https://uplay.com/{}",
"Battle.net":"https://battle.net/{}",
"GOG":"https://gog.com/u/{}",
"HumbleBundle":"https://humblebundle.com/{}",
"GreenManGaming":"https://greenmangaming.com/{}",
"Fanatical":"https://fanatical.com/en/user/{}",
"IndieGala":"https://indiegala.com/u/{}",
"GamersGate":"https://gamersgate.com/{}",
"BigFishGames":"https://bigfishgames.com/{}",
"Miniclip":"https://miniclip.com/{}",
"CoolMathGames":"https://coolmathgames.com/{}",
"Poki":"https://poki.com/{}",
"Y8":"https://y8.com/users/{}",
"Meetup":"https://meetup.com/{}",
"Eventbrite":"https://eventbrite.com/{}",
"Strava":"https://strava.com/athletes/{}",
"Garmin":"https://connect.garmin.com/modern/profiles/{}",
"Nike":"https://nike.com/{}",
"Adidas":"https://adidas.com/{}",
"UnderArmour":"https://underarmour.com/{}",
"MyFitnessPal":"https://myfitnesspal.com/{}",
"Fitbit":"https://fitbit.com/user/{}",
"MapMyFitness":"https://mapmyfitness.com/{}",
"DailyMile":"https://dailymile.com/people/{}",
"RunKeeper":"https://runkeeper.com/user/{}",
"Bodybuilding":"https://bodybuilding.com/{}",
"LiveStrong":"https://livestrong.com/{}",
"HealthUnlocked":"https://healthunlocked.com/{}",
"Patient":"https://patient.info/{}",
"Drugs.com":"https://drugs.com/{}",
"WebMD":"https://webmd.com/{}",
"MayoClinic":"https://mayoclinic.org/{}",
"MedHelp":"https://medhelp.org/{}",
"HealthCentral":"https://healthcentral.com/{}",
"WellSphere":"https://wellsphere.com/{}",
"Care2":"https://care2.com/{}",
"Gaia":"https://gaia.com/{}",
"MindBodyGreen":"https://mindbodygreen.com/{}",
"Greatist":"https://greatist.com/{}",
"Healthline":"https://healthline.com/{}",
"MedicalNews":"https://medicalnewstoday.com/{}",
"Medscape":"https://medscape.com/{}",
"RxList":"https://rxlist.com/{}",
"EMedicineHealth":"https://emedicinehealth.com/{}",
"HealthGrades":"https://healthgrades.com/{}",
"RateMDs":"https://ratemds.com/{}",
"Vitals":"https://vitals.com/{}",
"ZocDoc":"https://zocdoc.com/{}",
"Bookatable":"https://bookatable.com/{}",
"OpenTable":"https://opentable.com/{}",
"Resy":"https://resy.com/{}",
"Yelp":"https://yelp.com/{}",
"TripAdvisor":"https://tripadvisor.com/{}",
"Swarm":"https://swarmapp.com/{}",
"Gowalla":"https://gowalla.com/{}",
"Brightkite":"https://brightkite.com/{}",
"Loopt":"https://loopt.com/{}",
"Whrrl":"https://whrrl.com/{}",
"Foodspotting":"https://foodspotting.com/{}",
"Urbanspoon":"https://urbanspoon.com/{}",
"ChefsFeed":"https://chefsfeed.com/{}",
"GrubHub":"https://grubhub.com/{}",
"DoorDash":"https://doordash.com/{}",
"UberEats":"https://ubereats.com/{}",
"Postmates":"https://postmates.com/{}",
"Seamless":"https://seamless.com/{}",
"Delivery.com":"https://delivery.com/{}",
"EatStreet":"https://eatstreet.com/{}",
"BeyondMenu":"https://beyondmenu.com/{}",
"Slice":"https://slice.com/{}",
"MenuPages":"https://menupages.com/{}",
"AllMenus":"https://allmenus.com/{}",
"SinglePlatform":"https://singleplatform.com/{}",
"Locu":"https://locu.com/{}",
"Zmenu":"https://zmenu.com/{}",
"Foodler":"https://foodler.com/{}",
"BringMeThat":"https://bringmethat.com/{}",
"OrderUp":"https://orderup.com/{}",
"Waitr":"https://waitr.com/{}",
"BiteSquad":"https://bitesquad.com/{}",
"FoodNow":"https://foodnow.com/{}",
"MyPizza":"https://mypizza.com/{}",
"PizzaHut":"https://pizzahut.com/{}",
"Dominos":"https://dominos.com/{}",
"PapaJohns":"https://papajohns.com/{}",
"LittleCaesars":"https://littlecaesars.com/{}",
"ChuckECheese":"https://chuckecheese.com/{}",
"RedRobin":"https://redrobin.com/{}",
"Outback":"https://outback.com/{}",
"OliveGarden":"https://olivegarden.com/{}",
"Applebees":"https://applebees.com/{}",
"TGIFridays":"https://tgifridays.com/{}",
"Chilis":"https://chilis.com/{}",
"BuffaloWildWings":"https://buffalowildwings.com/{}",
"HardRockCafe":"https://hardrockcafe.com/{}",
"PlanetHollywood":"https://planethollywood.com/{}",
"RainforestCafe":"https://rainforestcafe.com/{}",
"DaveAndBusters":"https://daveandbusters.com/{}",
"Benihana":"https://benihana.com/{}",
"CheesecakeFactory":"https://thecheesecakefactory.com/{}",
"PFChangs":"https://pfchangs.com/{}",
"BucaDiBeppo":"https://bucadibeppo.com/{}",
"Carabbas":"https://carabbas.com/{}",
"MacaroniGrill":"https://macaronigrill.com/{}",
"Maggianos":"https://maggianos.com/{}",
"UnoPizzeria":"https://unopizzeria.com/{}",
"YardHouse":"https://yardhouse.com/{}",
"RockBottom":"https://rockbottom.com/{}",
"GordonBiersch":"https://gordonbiersch.com/{}",
"OldChicago":"https://oldchicago.com/{}",
"BJsRestaurants":"https://bjsrestaurants.com/{}",
"TwinPeaks":"https://twinpeaksrestaurant.com/{}",
"Hooters":"https://hooters.com/{}",
"WingHouse":"https://winghouse.com/{}",
"BonefishGrill":"https://bonefishgrill.com/{}",
"Seasons52":"https://seasons52.com/{}",
"CapitalGrille":"https://thecapitalgrille.com/{}",
"RuthChris":"https://ruthschris.com/{}",
"MortonSteak":"https://mortonsteakhouse.com/{}",
"FlemingSteak":"https://flemingssteakhouse.com/{}",
"SmithWollensky":"https://smithwollensky.com/{}",
"DelFriscos":"https://delfriscos.com/{}",
"Sullivans":"https://sullivanssteakhouse.com/{}",
"StripHouse":"https://striphouse.com/{}",
"TexasRoadhouse":"https://texasroadhouse.com/{}",
"LogansRoadhouse":"https://logansroadhouse.com/{}",
"LonghornSteakhouse":"https://longhornsteakhouse.com/{}",
"OutbackSteakhouse":"https://outbacksteakhouse.com/{}",
"Saltgrass":"https://saltgrass.com/{}",
"FamousDaves":"https://famousdaves.com/{}",
"SmokeyBones":"https://smokeybones.com/{}",
"Dickeys":"https://dickeys.com/{}",
"SonnyWilliams":"https://sonnywilliamsbbq.com/{}",
"Bandanas":"https://bandanasbbq.com/{}",
"Lucilles":"https://lucillesbbq.com/{}",
"RudyBBQ":"https://rudybbq.com/{}",
"BBQKing":"https://bbqking.com/{}",
"MissionBBQ":"https://missionbbq.com/{}",
"ShaneBBQ":"https://shanebbq.com/{}",
"FamousWings":"https://famouswings.com/{}",
"WingStreet":"https://wingstreet.com/{}",
"WingZone":"https://wingzone.com/{}",
"Wingstop":"https://wingstop.com/{}",
"BuffaloJoes":"https://buffalojoes.com/{}",
"WingFactory":"https://wingfactory.com/{}",
"WingsOver":"https://wingsover.com/{}",
"WingsExpress":"https://wingsexpress.com/{}",
"WingsPlus":"https://wingsplus.com/{}",
"WingsEtc":"https://wingsetc.com/{}",
"WingsNThings":"https://wingsnthings.com/{}",
"WingsToGo":"https://wingstogo.com/{}",
"JustWings":"https://justwings.com/{}",
"Wingman":"https://wingmanwings.com/{}",
"WingHouse":"https://winghouse.com/{}",
"WingBowl":"https://wingbowl.com/{}",
"WingFest":"https://wingfest.com/{}",
"WingCookOff":"https://wingcookoff.com/{}",
"WingWorld":"https://wingworld.com/{}",
"WingUniverse":"https://winguniverse.com/{}",
"WingGalaxy":"https://winggalaxy.com/{}",
"WingPlanet":"https://wingplanet.com/{}",
"WingStar":"https://wingstar.com/{}",
"WingSun":"https://wingsun.com/{}",
"WingMoon":"https://wingmoon.com/{}",
"WingEarth":"https://wingearth.com/{}",
"WingMars":"https://wingmars.com/{}",
"WingJupiter":"https://wingjupiter.com/{}",
"WingSaturn":"https://wingsaturn.com/{}",
"WingUranus":"https://winguranus.com/{}",
"WingNeptune":"https://wingneptune.com/{}",
"WingPluto":"https://wingpluto.com/{}",
"WingMercury":"https://wingmercury.com/{}",
"WingVenus":"https://wingvenus.com/{}",
"WingAsteroid":"https://wingasteroid.com/{}",
"WingComet":"https://wingcomet.com/{}",
"WingMeteor":"https://wingmeteor.com/{}",
"WingRocket":"https://wingrocket.com/{}",
"WingShuttle":"https://wingshuttle.com/{}",
"WingSpace":"https://wingspace.com/{}",
"WingNASA":"https://wingnasa.com/{}",
"WingESA":"https://wingesa.com/{}",
"WingSpaceX":"https://wingspacex.com/{}",
"WingBlueOrigin":"https://wingblueorigin.com/{}",
"WingVirginGalactic":"https://wingvirgingalactic.com/{}",
"WingRocketLab":"https://wingrocketlab.com/{}",
"WingRelativity":"https://wingrelativity.com/{}",
"WingAstra":"https://wingastra.com/{}",
"WingFirefly":"https://wingfirefly.com/{}",
"WingAevum":"https://wingaevum.com/{}",
"WingXCorp":"https://wingxcorp.com/{}",
"WingSpaceDev":"https://wingspacedev.com/{}",
"WingOrbital":"https://wingorbital.com/{}",
"WingLockheed":"https://winglockheed.com/{}",
"WingBoeing":"https://wingboeing.com/{}",
"WingNorthrop":"https://wingnorthrop.com/{}",
"WingRaytheon":"https://wingraytheon.com/{}",
"WingGeneralDynamics":"https://winggd.com/{}",
"WingBAESystems":"https://wingbae.com/{}",
"WingHoneywell":"https://winghoneywell.com/{}",
"WingL3Harris":"https://wingl3harris.com/{}",
"WingLeidos":"https://wingleidos.com/{}",
"WingSAIC":"https://wingsaic.com/{}",
"WingCACI":"https://wingcaci.com/{}",
"WingBoozAllen":"https://wingboozallen.com/{}",
"WingAccenture":"https://wingaccenture.com/{}",
"WingDeloitte":"https://wingdeloitte.com/{}",
"WingPwC":"https://wingpwc.com/{}",
"WingKPMG":"https://wingkpmg.com/{}",
"WingEY":"https://wingey.com/{}",
"WingMcKinsey":"https://wingmckinsey.com/{}",
"WingBCG":"https://wingbcg.com/{}",
"WingBain":"https://wingbain.com/{}",
"WingOliverWyman":"https://wingoliverwyman.com/{}",
"WingLEK":"https://winglek.com/{}",
"WingATKearney":"https://wingatkearney.com/{}",
"WingSimonKucher":"https://wingsimonkucher.com/{}",
"WingZSAssociates":"https://wingzs.com/{}",
"WingClearView":"https://wingclearview.com/{}",
"WingPutnam":"https://wingputnam.com/{}",
"WingHealthAdvances":"https://winghealthadvances.com/{}",
"WingTrinity":"https://wingtrinity.com/{}",
"WingGuidehouse":"https://wingguidehouse.com/{}",
"WingGrantThornton":"https://winggrantthornton.com/{}",
"WingRSM":"https://wingrsm.com/{}",
"WingCBIZ":"https://wingcbiz.com/{}",
"WingMossAdams":"https://wingmossadams.com/{}",
"WingCrowe":"https://wingcrowe.com/{}",
"WingBDO":"https://wingbdo.com/{}",
"WingCliftonLarsonAllen":"https://wingcliftonlarsonallen.com/{}",
"WingDHG":"https://wingdhg.com/{}",
"WingEisnerAmper":"https://wingeisneramper.com/{}",
"WingMarcum":"https://wingmarcum.com/{}",
"WingCohnReznick":"https://wingcohnreznick.com/{}",
"WingBKD":"https://wingbkd.com/{}",
"WingPlanteMoran":"https://wingplantemoran.com/{}",
"WingRehmann":"https://wingrehmann.com/{}",
"WingUHY":"https://winguhy.com/{}",
"WingAndersonAdvisors":"https://wingandersonadvisors.com/{}",
"WingKeiter":"https://wingkeiter.com/{}",
"WingPBMares":"https://wingpbmares.com/{}",
"WingAprio":"https://wingaprio.com/{}",
"WingElliotDavis":"https://wingelliotdavis.com/{}",
"WingLurie":"https://winglurie.com/{}",
"WingSchenck":"https://wingschenck.com/{}",
"WingWipfli":"https://wingwipfli.com/{}",
"WingRedpath":"https://wingredpath.com/{}",
"WingLGC":"https://winglgc.com/{}",
"WingHBE":"https://winghbe.com/{}",
"WingKRD":"https://wingkrd.com/{}",
"WingHCW":"https://winghcw.com/{}",
"WingSVA":"https://wingsva.com/{}",
"WingHSMC":"https://winghsmc.com/{}",
"WingMauldin":"https://wingmauldin.com/{}",
"WingHood":"https://winghood.com/{}",
"WingHORNE":"https://winghorne.com/{}",
"WingHAW":"https://winghaw.com/{}",
"WingHHM":"https://winghhm.com/{}",
"WingPYA":"https://wingpya.com/{}",
"WingHutcheson":"https://winghutcheson.com/{}",
"WingHughes":"https://winghughes.com/{}",
"WingWarren":"https://wingwarren.com/{}",
"WingHBM":"https://winghbm.com/{}",
"WingHendry":"https://winghendry.com/{}",
"WingHFWA":"https://winghfwa.com/{}",
"WingHaskell":"https://winghaskell.com/{}",
"WingHGM":"https://winghgm.com/{}",
"WingHCO":"https://winghco.com/{}",
"WingHaskell":"https://winghaskell.com/{}",
"WingHarris":"https://wingharris.com/{}",
"WingHaley":"https://winghaley.com/{}",
"WingHall":"https://winghall.com/{}",
"WingHale":"https://winghale.com/{}",
"WingHagedorn":"https://winghagedorn.com/{}",
"WingHagan":"https://winghagan.com/{}",
"WingHaddad":"https://winghaddad.com/{}",
"WingHackman":"https://winghackman.com/{}",
"WingHackbarth":"https://winghackbarth.com/{}",
"WingHabeeb":"https://winghabeeb.com/{}",
"WingHaas":"https://winghaas.com/{}",
"WingGwin":"https://winggwin.com/{}",
"WingGustafson":"https://winggustafson.com/{}",
"WingGurley":"https://winggurley.com/{}",
"WingGunderson":"https://winggunderson.com/{}",
"WingGulley":"https://winggulley.com/{}",
"WingGullett":"https://winggullett.com/{}",
"WingGuglielmo":"https://wingguglielmo.com/{}",
"WingGuffey":"https://wingguffey.com/{}",
"WingGudmundson":"https://winggudmundson.com/{}",
"WingGuckian":"https://wingguckian.com/{}",
"WingGudgel":"https://winggudgel.com/{}",
"WingGudde":"https://winggudde.com/{}",
"WingGubler":"https://winggubler.com/{}",
"WingGubbins":"https://winggubbins.com/{}",
"WingGubala":"https://winggubala.com/{}",
"WingGubac":"https://winggubac.com/{}",
"WingGubaa":"https://winggubaa.com/{}",
"WingGub":"https://winggub.com/{}",
"WingGuay":"https://wingguay.com/{}",
"WingGuastaferro":"https://wingguastaferro.com/{}",
"WingGuasp":"https://wingguasp.com/{}",
"WingGuarino":"https://wingguarino.com/{}",
"WingGuariglia":"https://wingguariglia.com/{}",
"WingGuarino":"https://wingguarino.com/{}",
"WingGuarente":"https://wingguarente.com/{}",
"WingGuarisco":"https://wingguarisco.com/{}",
"WingGuarino":"https://wingguarino.com/{}",
"WingGuariglia":"https://wingguariglia.com/{}",
"WingGuarisco":"https://wingguarisco.com/{}",
"WingGuarisco":"https://wingguarisco.com/{}",
"WingGuarisco":"https://wingguarisco.com/{}"
}

HEADERS={'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36'}
FOUND=[]

async def check_site(session,site,url):
    try:
        async with session.get(url,headers=HEADERS,timeout=8) as resp:
            if resp.status==200:
                FOUND.append(site)
                print(colorama.Fore.GREEN+f"[+] {site} -> {url}")
            else:
                print(colorama.Fore.RED+f"[-] {site}  {resp.status}")
    except Exception as e:
        print(colorama.Fore.YELLOW+f"[!] {site}  error")

async def reap(username):
    async with aiohttp.ClientSession(connector=aiohttp.TCPConnector(ssl=False,limit=300)) as session:
        tasks=[]
        for site,template in SITES.items():
            url=template.format(username)
            tasks.append(check_site(session,site,url))
        await asyncio.gather(*tasks)

def save_results(username):
    with open(f"{username}_hits.txt","w") as f:
        f.write("\n".join(FOUND))
    print(colorama.Fore.CYAN+f"\n[+] Saved {len(FOUND)} hits to {username}_hits.txt")

def main():
    colorama.init(autoreset=True)
    print(colorama.Fore.RED+LOGO)
    username=input("Username to hunt: ").strip()
    if not username:
        print("No username, no hunt.");return
    print(f"\nReaping {username} across {len(SITES)} sites...\n")
    start=time.time()
    asyncio.run(reap(username))
    save_results(username)
    print(f"\nDone in {time.time()-start:.2f}s")

if __name__=="__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\nAborted by user.")
